// Real projects from github.com/CHAHATMB — screenshots are pulled straight
// from each repository's README assets on raw.githubusercontent.com.
const raw = (repo, path, branch = "main") =>
  `https://raw.githubusercontent.com/CHAHATMB/${repo}/${branch}/${path}`;

export const PROJECTS = [
  {
    id: "vacart",
    name: "VaCart",
    tagline: "Real-time Indian Railway vacancy tracker",
    emoji: "🚆",
    kind: "Android · Kotlin",
    accent: "#7cf6b4",
    featured: true,
    stars: 5,
    body:
      "Native Android app that finds vacant berths on Indian Railway trains after chart preparation. Jetpack Compose + Material 3 UI, MVVM with Kotlin Flow driving async data streams and efficient REST polling.",
    features: [
      "Instant vacancy check per coach, right after chart prep",
      "Coach-level berth maps with bottom-sheet detail",
      "Full light / dark Material 3 theming",
      "Kestra-orchestrated data pipeline feeding the API",
    ],
    tags: ["Compose", "Kotlin", "Hilt", "Flow", "Coroutines", "Retrofit"],
    links: [{ label: "View on GitHub", href: "https://github.com/CHAHATMB/VaCart", primary: true }],
    frame: "phone",
    shots: [
      { src: raw("VaCart", "screenshots/home.png"), caption: "Home — search a train" },
      { src: raw("VaCart", "screenshots/traindetail.png"), caption: "Train details & schedule" },
      { src: raw("VaCart", "screenshots/coach.png"), caption: "Coach selection" },
      { src: raw("VaCart", "screenshots/coachbottom.png"), caption: "Coach info sheet" },
      { src: raw("VaCart", "screenshots/vacantberth.png"), caption: "Vacant berth chart" },
      { src: raw("VaCart", "screenshots/home_dark.png"), caption: "Home — dark theme" },
      { src: raw("VaCart", "screenshots/vacantberth_dark.png"), caption: "Berths — dark theme" },
    ],
  },
  {
    id: "passwordmanager",
    name: "Password Manager",
    tagline: "Offline AES-256 credential vault",
    emoji: "🔐",
    kind: "Android · Kotlin",
    accent: "#ffb782",
    featured: true,
    body:
      "A modern, open-source Android password manager: AES-256 encrypted Room storage, biometric unlock and Material 3 design. Nothing leaves the device — no cloud, maximum privacy.",
    features: [
      "AES-256 encryption over a local Room database",
      "Biometric / device-credential unlock gate",
      "Favourites for one-tap access to the logins you use daily",
      "Dark and light themes across every screen",
    ],
    tags: ["Compose", "Room", "AES-256", "Biometrics", "Material 3"],
    links: [{ label: "View on GitHub", href: "https://github.com/CHAHATMB/PasswordManager", primary: true }],
    frame: "phone",
    shots: [
      { src: raw("PasswordManager", "screen_shot/unlock.png"), caption: "Biometric unlock" },
      { src: raw("PasswordManager", "screen_shot/home.png"), caption: "Vault home" },
      { src: raw("PasswordManager", "screen_shot/add_screen.png"), caption: "Add a credential" },
      { src: raw("PasswordManager", "screen_shot/fav.png"), caption: "Favourites" },
      { src: raw("PasswordManager", "screen_shot/home_dark.png"), caption: "Vault — dark theme" },
      { src: raw("PasswordManager", "screen_shot/add_screen_dark.png"), caption: "Add — dark theme" },
    ],
  },
  {
    id: "cowall",
    name: "CoWall",
    tagline: "Shared lock-screen wallpaper, live",
    emoji: "🖼️",
    kind: "Android · Kotlin",
    accent: "#a99cff",
    body:
      "For friends, families and couples: set each other's lock screen in real time. Snap a selfie and it lands on their lock screen instantly — Firebase Realtime Database & Storage on an event-driven architecture with Koin DI.",
    features: [
      "Pair up through a room code — no accounts to manage",
      "Real-time wallpaper push via Firebase Realtime DB + Storage",
      "In-app camera with filters before you send",
      "Background worker applies the wallpaper without unlocking",
    ],
    tags: ["Kotlin", "Koin", "Firebase", "WorkManager"],
    links: [{ label: "View on GitHub", href: "https://github.com/CHAHATMB/CoWall", primary: true }],
    frame: "phone",
    shots: [
      { src: raw("CoWall", "screenshot/splashscreen.png"), caption: "Splash" },
      { src: raw("CoWall", "screenshot/createroomscreen.png"), caption: "Create a room" },
      { src: raw("CoWall", "screenshot/waitingscreen.png"), caption: "Waiting for a partner" },
      { src: raw("CoWall", "screenshot/homescreen.png"), caption: "Home" },
      { src: raw("CoWall", "screenshot/camerascreen.png"), caption: "Capture" },
      { src: raw("CoWall", "screenshot/filterscreen.png"), caption: "Filters" },
      { src: raw("CoWall", "screenshot/lockscreen.png"), caption: "Landed on their lock screen" },
    ],
  },
  {
    id: "bhuvmap",
    name: "bhuvMap",
    tagline: "Maharashtra land record viewer",
    emoji: "🗺️",
    kind: "Mobile · React Native",
    accent: "#8ad8ff",
    body:
      "A mobile front end for Maharashtra's Mahabhumi land records: search a village, pick a survey number and see the plot drawn on the map with its record, all in a UI that isn't from 2009.",
    features: [
      "Village and survey-number search over the Mahabhumi data",
      "Cadastral plot boundaries rendered over a live map",
      "Offline-friendly caching of viewed records",
      "Expo build shipping to Android",
    ],
    tags: ["React Native", "Expo", "TypeScript", "Maps"],
    links: [{ label: "View on GitHub", href: "https://github.com/CHAHATMB/bhuvMap", primary: true }],
    frame: "phone",
    shots: [
      { src: raw("bhuvMap", "screenshots/01.png"), caption: "Search a village" },
      { src: raw("bhuvMap", "screenshots/02.png"), caption: "Survey results" },
      { src: raw("bhuvMap", "screenshots/03.png"), caption: "Plot on the map" },
      { src: raw("bhuvMap", "screenshots/04.png"), caption: "Record detail" },
      { src: raw("bhuvMap", "screenshots/05.png"), caption: "Map layers" },
    ],
  },
  {
    id: "noshorts",
    name: "No Shorts, No Clickbait",
    tagline: "Firefox add-on for mindful YouTube",
    emoji: "🧩",
    kind: "Browser extension",
    accent: "#ff9ec7",
    body:
      "Published Firefox extension that strips Shorts out of YouTube, blurs clickbait thumbnails until you hover, and tracks cumulative watch time so the cost of the scroll is visible.",
    features: [
      "Removes Shorts shelves, tabs and feed entries",
      "Dynamic thumbnail blurring to kill clickbait pull",
      "Cumulative watch-time tracker with daily stats",
      "Live on addons.mozilla.org",
    ],
    tags: ["JavaScript", "WebExtensions", "DOM", "MV3"],
    links: [
      {
        label: "Install from Mozilla",
        href: "https://addons.mozilla.org/en-US/firefox/addon/yt-no-shorts-no-clickbait/",
        primary: true,
      },
      { label: "GitHub", href: "https://github.com/CHAHATMB/No-Shorts-No-Clickbait" },
    ],
    frame: "browser",
    shots: [
      { src: raw("No-Shorts-No-Clickbait", "docs/screenshots/screenshot1.png"), caption: "Feed with Shorts removed" },
      { src: raw("No-Shorts-No-Clickbait", "docs/screenshots/screenshot2.png"), caption: "Thumbnails blurred" },
      { src: raw("No-Shorts-No-Clickbait", "docs/screenshots/screenshot3.png"), caption: "Hover to reveal" },
      { src: raw("No-Shorts-No-Clickbait", "docs/screenshots/screenshot7.png"), caption: "Watch-time tracker" },
    ],
  },
  {
    id: "authkey",
    name: "AuthKey CLI",
    tagline: "TOTP codes from your terminal",
    emoji: "🔑",
    kind: "CLI · Node.js",
    accent: "#f3e08f",
    body:
      "Command-line manager for TOTP two-factor codes — add issuers, list them, and pull a fresh code without reaching for your phone. Secrets live encrypted on disk, modelled on Android's Keystore pattern.",
    features: [
      "Add, list and remove TOTP issuers from the shell",
      "Encrypted local secret store",
      "Copy-to-clipboard codes with countdown",
    ],
    tags: ["Node.js", "JavaScript", "TOTP", "Crypto"],
    links: [{ label: "View on GitHub", href: "https://github.com/CHAHATMB/authkey", primary: true }],
    frame: "terminal",
    shots: [],
    terminal: [
      "$ authkey add github --secret JBSWY3DPEHPK3PXP",
      "  ✔ issuer 'github' stored (encrypted)",
      "",
      "$ authkey get github",
      "  372 914   ▸ expires in 19s",
      "  copied to clipboard",
      "",
      "$ authkey ls",
      "  github   google   aws-root",
    ],
  },
];
